config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :cards, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection{ get :export}
    collection{ get :new_batch}
    collection{ post :import}
  end
  resources :lists, only: [:new, :create, :edit, :update, :destroy]
  resources :evaluations, only: [:new, :create, :edit, :update]

  root  'main#home'

  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signup',    to: 'main#home',              via: 'get'

  match '/help',        to: 'static_pages#help',            via: 'get'
  match '/kbshortcuts', to: 'static_pages#kbshortcuts',     via: 'get'
  match '/about',       to: 'static_pages#about',           via: 'get'
  match '/contact',     to: 'static_pages#contact',         via: 'get'

  match '/ok_guide',    to: 'users#ok_guide', via: 'get'
  
  match '/require_email_confirmation',    to: 'users#require_email_confirmation', via: 'get'
  match '/confirm_email',    to: 'users#confirm_email', via: 'get'

  match '/password_reset_request',    to: 'sessions#new_password_reset_request', via: 'get'
  match '/password_reset_request',    to: 'sessions#create_password_reset_request', via: 'post'
  match '/reset_password',    to: 'sessions#reset_password', via: 'get'
  match '/reset_password',    to: 'sessions#update_password', via: 'post'

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def home
    if signed_in?
      now = Time.zone.now
      @lists_global_report = List.build_id_hash(current_user.lists){|l| l.scope_report}
      @lists_charge_report = List.build_id_hash(current_user.lists){|l| l.chronos_report_flow(now)}
      @lists_coming_spans_report = List.build_id_hash(current_user.lists){|l| l.chronos_report_scheduled(now)}
    else
      redirect_to new_user_path
    end
  end
end

app/views/main/_chart.html.haml
- color_coming = "rgba(141, 184, 221, .5)" # blue from Bootstrap primary with transparency 50%
- color_now =    "rgba(255, 0,   0  , .05)"
- font = "11px Helvetica"
- label_color = "#999999" #bootstrap gray-light
- x_axis_color = label_color
- x_axis_tick_color = x_axis_color
- ready_count ||= 0
-# http://api.highcharts.com/highcharts#xAxis.gridLineDashStyle
:javascript
  $(function () {
    $('##{container_id}').highcharts({
      chart: {
        type: 'scatter',
        animation: false,
        backgroundColor:'rgba(255, 255, 255, 0)'
      },
      tooltip: {
        enabled: false
      },
      title: {
        text: null
      },
      credits: {
        enabled: false
      },
      xAxis: {
        title: null,
        // scale:
        min: 0,
        tickPositions: [0, #{max_span}],
        endOnTick: true,
        // design:
        lineColor: 'transparent', // Axis line color
        tickPosition: 'outside',
        tickWidth: 2,
        tickLength: 0,
        gridLineWidth: 5,
        tickColor: '#{x_axis_tick_color}',
        // labels:
        labels: {
          formatter: function() {
            if (this.value == 0)
              return "#{I18n.t("program.coming.chart.now", now_count: ready_count)}";
            else
              return "#{I18n.t("program.coming.chart.until1")} #{pluralize( scale_value, I18n.t("unit.#{scale_label}"))} #{I18n.t("program.coming.chart.until2")}";
          },
          style: {
            color: '#{label_color}',
            font: '#{font}'
          }
        }
      },
      yAxis: {
        title: null,
        labels: {
          enabled: false  // hide y values
        },
        gridLineWidth: 2,
        gridLineDashStyle: 'Dot',
        gridLineColor: '#{x_axis_color}'
      },
      legend: {
        enabled: false
      },
      plotOptions: {
        scatter: {
          marker: {
            radius: 5
          }
        },
        series: {
          animation: false
        }
      },
      series: [{
        color: '#{color_coming}',
        data:
          #{
            spans.map{|span| [span,0]}.to_json
          },
        marker: {
          symbol: 'circle'
        }
      },
      {
        color: '#{color_now}',
        data:
          #{
            Array.new(ready_count, [0,0]).to_json
          }
      }
      ]
    });
  });

app/views/main/_default_program_overview.html.haml
%h3= I18n.t("monitor.default_program.title")
%p
  = link_to( I18n.t("monitor.default_program.review_link"), new_evaluation_path, class: "btn btn-primary")
  %br
  = render "default_program_overview_inline", stats: @capacity_stats[:global], day_max: @capacity_stats[:day_max]

app/views/main/_global_controls.html.haml
= link_to( I18n.t("monitor.global_controls.new_cards_link"), new_card_path, accesskey: 'l' , class: "btn btn-success btn-sm")
= link_to( new_card_path(list_name: list_item.name), class: "btn btn-success btn-xs", accesskey: 'l', rel: I18n.t("monitor.global_controls.new_cards_link")){ haml_tag :span, :class => "glyphicon glyphicon-plus"; haml_concat "List"}
= link_to( I18n.t("monitor.global_controls.new_list_link"), new_list_path, class: "btn btn-success btn-sm")

app/views/main/_list_overview.html.haml
-#%h3= I18n.t('monitor.list_overview.title') 
-#= link_to( new_list_path, class: "btn btn-success btn-sm", data: { keybinding: access_key(:new_list)}, rel: I18n.t("monitor.global_controls.new_cards_link")){ haml_tag :span, :class => "glyphicon glyphicon-plus"; haml_concat I18n.t("models.list.list").capitalize}
%table.table
  -#%tr
  -#  %th= I18n.t('monitor.list_overview.table.header.list') 
  -#  %th
  -#  %th.charge.col-sm-2= I18n.t('program.charge.title')
  -#  -#%th= I18n.t('program.charge.title2')
  -#  %th= I18n.t('program.coming.title')
  -#  %th.list-overview-controls= I18n.t('monitor.list_overview.table.header.actions')
  = render partial: 'list_overview_item', collection: current_user.lists.display_order, as: :list_item
  %tr
    %td{ colspan: 6}
      = link_to( new_list_path, class: "btn btn-success btn-xs", data: { keybinding: access_key(:new_list)}, rel: I18n.t("monitor.global_controls.new_cards_link")){ haml_tag :span, :class => "glyphicon glyphicon-plus"; haml_concat List.model_name.human}

app/views/main/_list_overview_item.html.haml
- global_report = @lists_global_report[list_item.id]
- charge_report = @lists_charge_report[list_item.id]
- coming_report = @lists_coming_spans_report[list_item.id]

%tr

  %td
    = link_to( new_card_path(list_name: list_item.name), class: "btn btn-success btn-xs", rel: I18n.t("monitor.list_overview.table.body.new_cards_link")){ haml_tag :span, :class => "glyphicon glyphicon-plus";}

  %td
    .list_name
      = link_to list_item.name, cards_path(list_name: list_item.name)
    - if global_report[:reverse]
      %small.reverse!= I18n.t('monitor.list_overview.table.body.reverse')
    %small!= pluralize(global_report[:total], Card.model_name.human.downcase)

  = render "list_overview_item_chronos_report", 
    charge_report: charge_report, 
    coming_report: coming_report,
    coming_max_span: @lists_coming_spans_report[ :max_coming_span],
    list_card_count: global_report[:total],
    list: list_item,
    list_review_link: new_evaluation_path(list_name: list_item.name), 
    list_review_link_tabindex: list_item_counter + 1

  %td.list-overview-controls
    -#= link_to( new_card_path(list_name: list_item.name), class: "btn btn-success btn-xs", rel: I18n.t("monitor.list_overview.table.body.new_cards_link")){ haml_tag :span, :class => "glyphicon glyphicon-plus"}
    -#= link_to( I18n.t("monitor.list_overview.table.body.list_view_link"), cards_path(list_name: list_item.name), class: "btn btn-primary btn-xs"){ haml_tag :i, :class => "glyphicon glyphicon-th-list"}
    -#= link_to( cards_path(list_name: list_item.name), class: "btn btn-primary btn-xs", rel: I18n.t("monitor.list_overview.table.body.list_view_link")){ haml_tag :span, :class => "glyphicon glyphicon-th-list"}
    = link_to( edit_list_path(list_item), class: "btn btn-warning btn-xs", rel: I18n.t("monitor.list_overview.table.body.list_edit_link")){ haml_tag :span, :class => "glyphicon glyphicon-cog"}
    = link_to( list_path(list_item), method: :delete, data:{ confirm: I18n.t("monitor.list_overview.table.body.list_destroy_confirmation", list_name: list_item.name)}, class: "btn btn-danger btn-xs", rel: I18n.t("monitor.list_overview.table.body.list_destroy_link")){ haml_tag :span, :class => "glyphicon glyphicon-remove"}

app/views/main/_list_overview_item_chronos_report.html.haml
%td
  - if list_card_count != 0

    - if list.review_mode == "mail"
      -# mail

      - if list.user.email_confirmed?

        .rk
          %span.glyphicon.glyphicon-envelope
          -#= "#{I18n.t('program.review_mode')}," 
          = "#{charge_report[:chronos_capacity_volume]} #{t('program.review_every')} #{list.review_mail_reccurency_str(:abr)}"
        - if charge_report[:ready] != 0 
          %small
            - ready_text = capture_haml( "#{charge_report[:ready]}", I18n.t("program.review_anyw"), I18n.t("program.upto")){|count_text, review_text, upto_text| haml_tag(:b, review_text); haml_tag(:span, class: "badge"){ haml_concat(count_text) } }
            = link_to ready_text, list_review_link, class: "btn btn-default btn-sm"
        - else
          .rk.no= I18n.t("program.charge.ready_none")
      - else
        .rk
          -#%span.glyphicon.glyphicon-warning-sign 
          -# TODO I18n
          Waiting for 
          != link_to t('program.email_addr_conf'), require_email_confirmation_url
    - elsif list.review_mode == "no_mail"
      -# no mail

      - if charge_report[:ready] != 0
        -# ready
        - ready_text = capture_haml( "#{charge_report[:ready]}", I18n.t("program.review_link"), I18n.t("program.upto")){|count_text, review_text, upto_text| haml_tag(:b, review_text); haml_tag(:span, class: "badge"){ haml_concat(count_text) } }
        = defined?(list_review_link) ? link_to( ready_text, list_review_link, class: "btn btn-primary btn-sm", tabindex: list_review_link_tabindex,  accesskey: access_key(:review)) : ready_text
      - else
        .rk.no= I18n.t("program.charge.ready_none")

      - if charge_report[:capacity] 
        -# charge
        %br
        .rk
          = I18n.t('program.charge.upto')
          %strong= charge_report[:chronos_capacity_volume]
          %strong= "#{Card.model_name.human.downcase.pluralize(charge_report[:chronos_capacity_volume])}"
          = I18n.t('program.charge.per')
          %strong= "#{distance_of_time_in_words(charge_report[:chronos_capacity_tspan])}"
          -# capacity settings
          - if charge_report[:pending] != 0  
            = " (#{charge_report[:pending]} #{I18n.t("program.charge.pending")})"
          -# else
            %small.no!= I18n.t("program.charge.pending_none")

%td
  -# coming
  - if list_card_count != 0 and list.review_mode != "paused"
    - if coming_report.present? #or charge_report[:ready] > 0
      - coming_max_span = coming_report.max || 0 # coming_max_span for global max
      - container_id = "container_#{SecureRandom.hex(10)}"
      -#%small= "#{I18n.t("program.coming.coming", coming_count: coming_report.count)}"
      .rk
        = "#{I18n.t("program.coming.coming")}"
        = "(#{coming_report.count}):"
      .chart{id: "#{container_id}", class: "chart"}
        - scale = scale_computer( coming_max_span.round)
        -# coming_report = coming_report.map{|s| seconds_to(s, scale[:label])}
        -# coming_max_span = seconds_to( coming_max_span, scale[:label])
        = render 'chart',
          container_id: "#{container_id}", 
          spans: coming_report, 
          max_span: scale[:value].send(scale[:label]), 
          scale_value: scale[:value], 
          scale_label: scale[:label]
    - else
      .rk.no= I18n.t("program.coming.none")

app/views/main/home.html.haml
- guides = current_user.guide
- checked_guides = guides.select{|label, is_checked| is_checked}.keys

- if ([:welcome, :letstour] - checked_guides).present? # only display row if some aren t checked
  .row
    = render "shared/guide", label: :welcome
    = render "shared/guide", label: :letstour, previous: :welcome

- provide_title I18n.t('monitor.title')

- if ([:list, :review, :progression, :settings] - checked_guides).present? # only display row if some aren t checked
  .row
    .col-md-3
      = render "shared/guide", label: :list, previous: :letstour
    .col-md-3
      = render "shared/guide", label: :review, previous: :add
    .col-md-3
      = render "shared/guide", label: :progression, display_cdt: (not guides[:progression] and current_user.evaluations.count > 0), previous: :review
    .col-md-3
      = render "shared/guide", label: :settings, previous: :progression

- if current_user.lists.empty? # no card && no list
  .row
    .col-sm-4.col-sm-offset-4
      %h2!= I18n.t('monitor.overview.no_cards')
      %br
      %p
        = link_to( I18n.t("monitor.global_controls.new_cards_link"), new_card_path, class: "btn btn-success btn-sm btn-block")
        = link_to( I18n.t("monitor.global_controls.new_list_link"), new_list_path, class: "btn btn-success btn-sm btn-block")
- if current_user.lists.any?
  =# link_to( new_list_path, class: "btn btn-success btn-sm", data: { keybinding: access_key(:new_list)}, rel: I18n.t("monitor.global_controls.new_cards_link")){ haml_tag :span, :class => "glyphicon glyphicon-plus"; haml_concat I18n.t("models.list.list").capitalize}
  =# link_to( new_card_path, class: "btn btn-success btn-sm", data: { keybinding: access_key(:new_card)}, rel: I18n.t("monitor.global_controls.new_cards_link")){ haml_tag :span, :class => "glyphicon glyphicon-plus"; haml_concat I18n.t("models.card.card").capitalize}
  %p
    = render 'list_overview'
  =# link_to( new_list_path, class: "btn btn-success btn-sm", rel: I18n.t("monitor.global_controls.new_cards_link")){ haml_tag :span, :class => "glyphicon glyphicon-plus"; haml_concat I18n.t("models.list.list").capitalize}
  =# link_to( new_card_path, class: "btn btn-success btn-sm", rel: I18n.t("monitor.global_controls.new_cards_link")){ haml_tag :span, :class => "glyphicon glyphicon-plus"; haml_concat I18n.t("models.card.card").capitalize}

- if ([:add] - checked_guides).present?
  .row
    .col-md-3
      = render "shared/guide", label: :add, previous: :list