config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :cards, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection{ get :export}
    collection{ get :new_batch}
    collection{ post :import}
  end
  resources :lists, only: [:new, :create, :edit, :update, :destroy]
  resources :evaluations, only: [:new, :create, :edit, :update]

  root  'main#home'

  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signup',    to: 'main#home',              via: 'get'

  match '/help',        to: 'static_pages#help',            via: 'get'
  match '/kbshortcuts', to: 'static_pages#kbshortcuts',     via: 'get'
  match '/about',       to: 'static_pages#about',           via: 'get'
  match '/contact',     to: 'static_pages#contact',         via: 'get'

  match '/ok_guide',    to: 'users#ok_guide', via: 'get'
  
  match '/require_email_confirmation',    to: 'users#require_email_confirmation', via: 'get'
  match '/confirm_email',    to: 'users#confirm_email', via: 'get'

  match '/password_reset_request',    to: 'sessions#new_password_reset_request', via: 'get'
  match '/password_reset_request',    to: 'sessions#create_password_reset_request', via: 'post'
  match '/reset_password',    to: 'sessions#reset_password', via: 'get'
  match '/reset_password',    to: 'sessions#update_password', via: 'post'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :lists, dependent: :destroy
  has_many :cards, dependent: :destroy
  # REM one of:
  #has_many :evaluables, through: :cards, source_type: Word # add #evaluables to the model
  has_many :words, through: :cards, source: :evaluable, source_type: Word # add #words to the model
  has_many :evaluations, through: :cards
  has_many :card_metas, through: :cards, source: :meta

  serialize :guide

  before_save :unconfirm_email, :if => :email_changed?
  before_create :create_remember_token

  before_validation :set_fields_defaults
  before_create :normalize_email

  # TODO add a before_validation: exiger password si email changed

  validates :name, presence: true, length: { maximum: 50 }
  EMAIL_FORMAT = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email, presence: true, format: { with: EMAIL_FORMAT }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, :if => ->(){ password_digest == nil or self.email_changed? or password != nil} # TODO or password != nil ?!?!
  has_secure_password

  def build_card( evaluable, list={}, card={})
    new_card       = card.kind_of?(Hash) ? cards.find_or_initialize_by( card) : card
    new_card.list  = list.kind_of?(Hash) ? lists.find_or_initialize_by( list) : list
    new_card.evaluable ? new_card.evaluable.assign_attributes( evaluable) : new_card.evaluable = evaluable
    new_card.evaluable.card = new_card # so that evaluable get the card when calling #card before the card is saved
    new_card
  end
  
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.hash(token)
    Digest::SHA1.hexdigest(token.to_s) # to_s make sure nil token could be handled
  end

  # Email Confirmation

  def email_confirmed?
    return email_confirmed
  end

  def send_email_confirmation!
    if send_email_confirmation_allowed?
      token = User.new_remember_token
      UserMailer.email_confirmation_mail( email, token).deliver
      return update_attributes( email_confirmation_last_sent_date: Time.zone.now, email_confirmation_token: token)
    else
      return false
    end
  end

  def confirm_email!(token)
    if email_confirmation_last_sent_date > 1.day.ago and token == email_confirmation_token
      return update_attributes( email_confirmed: true)
    else
      return false
    end
  end

  def unconfirm_email!
    unconfirm_email
    save
  end

  # Reset password

  def send_password_reset!
    if send_password_reset_allowed?
      token = User.new_remember_token
      UserMailer.password_reset_mail( self, token).deliver
      return update_attributes( password_reset_last_sent_at: Time.zone.now, password_reset_token: token)
    else
      return false
    end
  end

  # return true / false
  def reset_password!(token, password_param)
    if password_reset_last_sent_at > 1.hour.ago and token == password_reset_token
      return update_attributes( password_param.merge!( password_reset_token: nil))
    else
      return false
    end
  end
 
  # TODO: Test if the review starts with the right card
  # RK: Not hooked on the after_create callback not to make tests slow
  def build_initial_content
    path = "content/"
    [
      ["History-50_Most_important_dates", {
        reverse: false,
        chronos_success_min_tspan: 7.days,
        chronos_capacity_volume: 3,
        chronos_capacity_tspan: 7.days,
        review_mail_recurrency: nil

      }],
      ["German_-_From_everyday_life",     { 
        reverse: true,
        chronos_success_min_tspan: 1.hour,
        chronos_capacity_volume: 15,
        chronos_capacity_tspan: 1.day,
        review_mail_recurrency: nil
      }],
      ["What_I_noticed_I_should_do",      {
        reverse: false,
        chronos_success_min_tspan: 1.hour,
        chronos_capacity_volume: nil,
        chronos_capacity_tspan: nil,
        review_mail_recurrency: nil
      }]
    ].each do |filename, config|
      full_path = path + filename + ".csv"
      list = self.lists.create( name: filename.gsub(/_/, " ").gsub(/-/, " - "))
      Pavlov.import_words( File.new(full_path)) do |content, tip|
        build_card( Word.new( content: content, tip: tip), list)
      end
      list.update_attributes( config ) if config
    end
  end

  private

  def unconfirm_email
    self.email_confirmed = false
    self.email_confirmation_token = nil
  end
  
  # TODO manage error display through flash parameter or writting errors in the model.
  # TODO move the 3. hours in a config file ?
  
  def send_email_confirmation_allowed?
    return (not email_confirmed?) && (email_confirmation_last_sent_date == nil || email_confirmation_last_sent_date < 3.hours.ago)
  end

  def send_password_reset_allowed?
    return (password_reset_last_sent_at.nil? or (password_reset_last_sent_at  < 1.hour.ago))
  end

  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end

  def normalize_email
    email.downcase!
  end

  def set_fields_defaults
    self.guide ||= {}
    raise( "User#guide wrong key") if not self.guide.kind_of?(Hash)
    true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include InviteCodeHelper
  before_action :signed_in_user,  except: [:new, :create]
  #before_action :correct_user,    except: [:new, :create]


  def new
    @user = User.new
    render layout: false
  end

  def show
    #@user = User.find(params[:id])
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      if not invite_code_activated? or valid_invite_code?(params[:invite_code]) or Rails.env.test?
        if @user.save
          #flash[:success] = I18n.t('controllers.users.create.success')
          sign_in @user
          @user.build_initial_content
          redirect_to root_url
        else
          render 'new', layout: false
        end
      else
        SignupAttempt.create( invite_code: params[:invite_code], name: params[:user][:name], email: params[:user][:email] )
        render 'no_invite'
      end
    else
      render 'new', layout: false
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:success] = I18n.t('controllers.users.update.success')
      redirect_to @user
    else
      render 'edit'
    end
  end

  # Guide

  def ok_guide
    guide = current_user.guide
    guide[ params[:guide].to_sym] = true
    current_user.update_attribute( :guide, guide)
    redirect_back
  end

  # Email Confirmation

  def require_email_confirmation
    if current_user.send_email_confirmation!
      flash[:success] = t('controllers.users.require_email_confirmation.success')
    else
      flash[:warning] = t('controllers.users.require_email_confirmation.warning')
    end
    redirect_back
  end

  def confirm_email
    token = params[:token]
    if current_user.confirm_email!(token)
      flash[:success] = t('controllers.users.confirm_email.success')
    else
      flash[:warning] = t('controllers.users.confirm_email.warning')
    end
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # Before filters

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end
end

app/views/users/_new_edit.html.haml
- provide_title I18n.t("users.#{action}.title")
.row
  .col-md-4.col-md-offset-4
    = form_for(@user) do |f|
      = render 'shared/user_form', f: f
      = f.submit I18n.t("users.#{action}.submit"), class: "btn form-first-btn form-save-btn"
      = link_to( I18n.t("users.#{action}.back"), user_path(@user), class: "btn form-second-btn form-discard-btn") if @user.id

app/views/users/edit.html.haml
= render 'new_edit', action: 'edit'

app/views/users/new.html.haml
!!!
%html
  = render 'layouts/head'
  %body
    = render 'layouts/header' 
    .welcome-frame
      .row.welcome-top-row
        .container
          - provide_title I18n.t('application.logo')
          %h2.welcome-sub-subtitle Learning & Self-Conditioning with Spaced Repetition
          -#Spaced repetition training
          -# Lazy reliable learning with spaced repetition
          -# Spaced repetition learning
          .col-sm-4.col-sm-offset-2
            .welcome-sign-form
              = form_for(@user) do |f|
                = render 'shared/user_form', f: f
                .welcome-form-bottom
                  .welcome-sign-up
                    = text_field_tag(:invite_code, nil, autocomplete: "off", class: "form-control", placeholder: 'Invite code?') if invite_code_activated?
                    = f.submit I18n.t("welcome.submit"), class: "btn form-first-btn sign-btn"
                  .text-right
                    %span.welcome-sign-in.welcome-big
                      or
                      %strong.text-center= link_to t('welcome.signin'), signin_url
          .col-sm-5
            .welcome-features
              -# TODO make a helper to do that
              %ul.list-unstyled.icon-list.welcome-big
                %li.glyphicon-pencil 
                  %strong Create flash-cards
                  %br 
                  about anything you want to 
                  %strong train
                -# glyphicon-pencil glyphicon-th-list glyphicon-list-alt
                %li.glyphicon-calendar 
                  -# glyphicon-stats
                  Pavlov <strong>understands</strong> when a card 
                  %br is worth to be reviewed again
                -# monitors, manages, understand
                -# glyphicon-random glyphicon-dashboard glyphicon-tasks glyphicon-time
                -# %li.glyphicon-send Pavlov can <strong>alert</strong> you by mail

                %li.glyphicon-cog
                  %strong Review your cards
                  %br focusing on the content only

                %li.glyphicon-pushpin
                  Set a <strong>daily or weekly</strong> amount of work 
                  %br or configure <strong>review mails</strong>
                  -# .glyphicon-send .glyphicon-envelope
                %br
                %br
                %li.glyphicon-arrow-right.welcome-features-ccl-li
                  %strong.welcome-features-ccl Carefree
                  learning
                  -#%br Pavlov pays attention for you.
                  -# Careless learning.
                  -# Self-sustaining
                  -# Just a matter of time before you have it learned.
                  -# sooner or later, you'll have it learned.
                  -# glyphicon-chevron-right glyphicon-play glyphicon-hand-right
                  -# Let the time serve you:
      .row.welcome-middle-row
        .container.welcome-sub-subtitle.welcome-big 
          %h2.welcome-sub-subtitle Create and let Pavlov do the boring stuff
          .col-sm-4
            %ul.list-unstyled.icon-list
              %li.glyphicon-pencil
                Create a 
                %strong flash-card 
                for anything that you want to 
                %strong train on.
                %ul.welcome-ul
                  %li <strong>Languages</strong>
                  %li New <strong>habits</strong> to get into
                  %li <strong>History</strong>
                  %li ...
          .col-sm-4
            %ul.list-unstyled.icon-list
              %li.glyphicon-cog
                -# glyphicon-retweet
                Pavlov let you
                <strong>review your content</strong>
                and
                <strong>assess your assimilation</strong>:
                = image_tag("com/reviewing_and_assessment.jpg", style: "width: 100%; margin-top: 20px; margin-bottom: 10px;")
                -#%li.glyphicon-adjust
                -#.glyphicon-sort
                -#.glyphicon-edit
                -#It takes this opportunity to let you
          .col-sm-4
            %ul.list-unstyled.icon-list
              %li.glyphicon-calendar
                Using your assessments, Pavlov knows 
                %strong when a card is worth being reviewed again.
              %li.glyphicon-envelope
                You can 
                %strong configure a daily or weekly mail 
                for each list of cards independently 
          = image_tag("com/mustaches-light-blue.jpg", style: "width: 100%; margin-top: 10px;")
          = image_tag("com/screenshot.jpg", style: "width: 100%; margin-top: 10px;")
      -#.container
      -#  = render 'layouts/footer' 
      .row#welcome-low-row
        .container
          = render 'layouts/footer'

app/views/users/no_invite.html.haml
- provide_title I18n.t('users.no_invite.title')
.row
  .col-md-4.col-md-offset-4
    = I18n.t('users.no_invite.message')

app/views/users/show.html.haml
- provide_title I18n.t('users.show.title')
.row
  .col-md-4.col-md-offset-4
    = form_for @user do |f|

      = f.label :name # TODO name from ActiveRecord
      %p= @user.name

      = f.label :email
      %p= @user.email

      = link_to I18n.t('users.show.edit_user_link'), edit_user_path(@user), class: "btn form-first-btn edit-btn"