config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :cards, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection{ get :export}
    collection{ get :new_batch}
    collection{ post :import}
  end
  resources :lists, only: [:new, :create, :edit, :update, :destroy]
  resources :evaluations, only: [:new, :create, :edit, :update]

  root  'main#home'

  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signup',    to: 'main#home',              via: 'get'

  match '/help',        to: 'static_pages#help',            via: 'get'
  match '/kbshortcuts', to: 'static_pages#kbshortcuts',     via: 'get'
  match '/about',       to: 'static_pages#about',           via: 'get'
  match '/contact',     to: 'static_pages#contact',         via: 'get'

  match '/ok_guide',    to: 'users#ok_guide', via: 'get'
  
  match '/require_email_confirmation',    to: 'users#require_email_confirmation', via: 'get'
  match '/confirm_email',    to: 'users#confirm_email', via: 'get'

  match '/password_reset_request',    to: 'sessions#new_password_reset_request', via: 'get'
  match '/password_reset_request',    to: 'sessions#create_password_reset_request', via: 'post'
  match '/reset_password',    to: 'sessions#reset_password', via: 'get'
  match '/reset_password',    to: 'sessions#update_password', via: 'post'

end

app/models/card.rb
class Card < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :user

  belongs_to :list
  validates_presence_of :list
  validates_associated :list

  # REM autosave: true so that WordReverse and Word are UPDATED when card is updated
  belongs_to :evaluable, polymorphic: true, dependent: :destroy, autosave: true 
  validates_presence_of :evaluable
  validates_associated :evaluable

  has_many :evaluations, dependent: :destroy

  # REM without table name, causes column name ambiguity error when joined.
  scope :desc, ->{ order( "#{table_name}.created_at DESC")}

  after_update :update_reverse_list
  def update_reverse_list
    reverse_card = self.evaluable.reverse.card
    reverse_card.update_attributes( list: self.list) if reverse_card.list != self.list
  end
  
  include Program::Chronos::CardHook
  
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :signed_in_user

  # TODO Patch model to be able to build a polymorphic 1 to 1 association

  def new
    @card = current_user.build_card( Word.new, name: params[:list_name] || list_last_name)
    @back_url = flash[:back_url] || request.referer
  end

  def create
    @card = current_user.build_card( Word.new( word_params), list_name_param)
    @back_url = params[:back_url]
    if @card.save
      flash[:success] = I18n.t('controllers.cards.create.success')
      flash[:back_url] = @back_url
      redirect_to new_card_url
    else
      render 'new'
    end
  end

  # TODO Handle if not found
  def edit
    @card = current_user.cards.find_by( id_param)
    @back_url = request.referer
  end

  def update
    @card = current_user.build_card( word_params, list_name_param, id_param)
    @back_url = params[:back_url]
    if @card.save
      flash[:success] = I18n.t('controllers.cards.update.success')
      redirect_to @back_url
    else
      render 'edit'
    end
  end

  def destroy
    if card = current_user.cards.find_by( id_param) and card and card.destroy
      flash[:success] = I18n.t("controllers.cards.destroy.success")
    else
      flash[:warning] = I18n.t("controllers.cards.destroy.warning")
    end
    redirect_back
  end

  def index
    if not @list = current_user.lists.find_by( name: params[:list_name])
      flash[:warning] = I18n.t('controllers.cards.index.warning')
      redirect_back
    end
  end

  def new_batch
    if not @list = current_user.lists.find_by( name: params[:list_name])
      flash[:warning] = I18n.t('controllers.cards.new_batch.warning')
      redirect_back
    end
  end

  def import
    @list = current_user.lists.find_or_initialize_by( name: params[:list_name])
    reverse = !!params[:reverse] || false
    if params[:file] and @list and @list.valid?
      count_success, count_fail = Pavlov.import_words( params[:file]) do |content, tip|
        content, tip = (tip || "?"), content if reverse
        current_user.build_card( Word.new( content: content, tip: tip), @list)
      end
      # TODO move in Card#import ?
      if count_fail == 0
        flash[:success] = I18n.t("controllers.cards.import.success", 
                                 count: Card.model_name.human(count: count_success))
      else
        flash[:info] = I18n.t("controllers.cards.import.info", 
                              count_success: Card.model_name.human(count: count_success), 
                              count_fail: Card.model_name.human(count: count_fail))
      end
      redirect_to new_card_url
    else
      flash.now[:warning] = I18n.t("controllers.cards.import.warning")
      render 'new_batch'
    end
  end

  # TODO move in index action ?
  def export
    # TODO move in Card#to_csv ?
    data = CSV.generate col_sep: "|" do |csv|
      csv << [Word.human_attribute_name(:content), Word.human_attribute_name(:tip), List.model_name.human]
      current_user.lists.all.each do |l|
        l.words.all.each do |w|
          csv << [w.content, w.tip, w.card.list.name].map{|s| s.gsub(/[^[:print:]]/i, '')}
        end
      end
    end

    respond_to do |format|
      #format.html
      format.csv do send_data data, 
                              type: 'text/csv; charset=utf-8; header=present', 
                              filename: Card.model_name.human.pluralize + "_" + I18n.t("application.name") + ".csv"
      end
    end
  end

private

  def helpers
    ActionController::Base.helpers
  end

  def list_last_name
    current_user.cards.desc.first.try{|c| c.list.name} || ""
  end

  def word_params opts={}
    params.require(:word).permit(:content, :tip)
  end

  # If the card has an evaluable already, it is updated with the evaluable argument. 
  # Otherwise, it is assigned with the evaluable argument.
  #def build_card( evaluable, list={}, card={})
  #  new_card       = card.kind_of?(Hash) ? current_user.cards.find_or_initialize_by( card) : card
  #  new_card.list  = list.kind_of?(Hash) ? current_user.lists.find_or_initialize_by( list) : list
  #  new_card.evaluable ? new_card.evaluable.assign_attributes( evaluable) : new_card.evaluable = evaluable
  #  new_card
  #end
end

app/views/cards/_card_form.html.haml
= render 'shared/error_messages', object: f.object.evaluable
= render 'shared/error_messages', object: f.object.list, prefix: List.model_name.human

= hidden_field_tag :back_url, @back_url

= fields_for :word, f.object.evaluable do |ff|
  = ff.label :card, I18n.t('cards.new.card')
  = ff.text_area :content, :rows => "3", placeholder: I18n.t('cards.new.content.placeholder'), autofocus: true, class: "card-front-side form-control"
  = ff.text_area :tip, :rows => "3", placeholder: I18n.t('cards.new.tip.placeholder'), class: "form-control"

= fields_for :list, f.object.list do |ff|
  = ff.label :name, 'List'
  = ff.text_field :name, class: "form-control", placeholder: List.human_attribute_name(:name)

app/views/cards/_card_item.html.haml
%tr
  %td!= card_item.evaluable.content
  %td!= card_item.evaluable.tip
  - dt = card_item.meta.next_evaluation_date - now
  %td!= dt < 0 ? I18n.t('cards.index.table.body.now') : distance_of_time_in_words( dt)
  - if @list.reverse
    - dt = card_item.evaluable.reverse.card.meta.next_evaluation_date - now
    %td!= dt < 0 ? I18n.t('cards.index.table.body.now') : distance_of_time_in_words( dt)
  %td
    .btn-group.btn-group-xs
      = link_to( I18n.t("cards.index.table.body.card_edit_link"), edit_card_path(card_item), class: "btn edit-btn")
      = link_to( I18n.t("cards.index.table.body.card_delete_link"), card_path(card_item), method: :delete, data: { confirm: I18n.t("cards.index.table.body.card_delete_confirmation")}, class: "btn delete-btn")

app/views/cards/_new_edit.html.haml
- provide_title I18n.t("cards.#{action}.title")

.row
  .col-md-4.col-md-offset-4

    -# normal creation
    = form_for(@card) do |f|
      = render 'card_form', f: f
      = f.submit I18n.t("cards.#{action}.submit"), class: "btn form-first-btn form-save-btn"
      = link_to I18n.t("cards.#{action}.back"), @back_url, class: "btn form-second-btn form-discard-btn"

    -# mass import
    - if action == 'new'
      = link_to( I18n.t("cards.#{action}.new_batch_link"), new_batch_cards_path( list_name: @card.list.name), class: "btn form-first-btn alt-btn")

app/views/cards/edit.html.haml
= render 'new_edit', action: 'edit'

app/views/cards/index.html.haml
- provide_title I18n.t('cards.index.title'), @list.name
- if @list.indexables.any?
  %table.table
    %tr
      %th= I18n.t('cards.index.table.header.content')
      %th= I18n.t('cards.index.table.header.tip')
      %th= I18n.t('cards.index.table.header.next_review')
      - if @list.reverse
        %th= I18n.t('cards.index.table.header.next_review_reverse')
      %th.col-xs-1.cards-index-controls= I18n.t('cards.index.table.header.control')
    = render partial: 'card_item', collection: @list.indexables.desc, :locals => {now: Time.zone.now}
    %tr
      %td{ colspan: 6}
        = link_to( new_card_path(list_name: @list.name), class: "btn btn-success btn-xs", rel: I18n.t("monitor.list_overview.table.body.new_cards_link")){ haml_tag :span, :class => "glyphicon glyphicon-plus"; haml_concat( Card.model_name.human)}
- else
  %p
    != I18n.t('cards.index.no_cards')
  %p
    = link_to( I18n.t("monitor.global_controls.new_cards_link"), new_card_path(list_name: @list.name), class: "btn btn-success btn-sm")

app/views/cards/new.html.haml
= render 'new_edit', action: 'new'

app/views/cards/new_batch.html.haml
- provide_title I18n.t('cards.new_batch.title')
.row
  .col-md-4.col-md-offset-4

    %p!= I18n.t('cards.new_batch.intro')

    .after-form
      %p!= I18n.t('cards.new_batch.manual_list', list_name: @list.name)
      = form_tag import_cards_path, multipart: true do
        = render 'shared/error_messages', object: @list

        = file_field_tag :file, class: "file-field form-control"

        = hidden_field_tag :list_name, @list.name
        = submit_tag I18n.t('cards.new_batch.submit'), data: { confirm: I18n.t("cards.new_batch.import_confirmation", list_name: @list.name)}, class: "btn add-btn"

    .after-form.form-field-comment
      %p!= I18n.t('cards.new_batch.manual_format_intro')
      %pre.form-field-comment= I18n.t('cards.new_batch.manual_format')
      %p!= I18n.t('cards.new_batch.manual_format_descr')