config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :cards, only: [:new, :create, :edit, :update, :index, :destroy] do
    collection{ get :export}
    collection{ get :new_batch}
    collection{ post :import}
  end
  resources :lists, only: [:new, :create, :edit, :update, :destroy]
  resources :evaluations, only: [:new, :create, :edit, :update]

  root  'main#home'

  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signup',    to: 'main#home',              via: 'get'

  match '/help',        to: 'static_pages#help',            via: 'get'
  match '/kbshortcuts', to: 'static_pages#kbshortcuts',     via: 'get'
  match '/about',       to: 'static_pages#about',           via: 'get'
  match '/contact',     to: 'static_pages#contact',         via: 'get'

  match '/ok_guide',    to: 'users#ok_guide', via: 'get'
  
  match '/require_email_confirmation',    to: 'users#require_email_confirmation', via: 'get'
  match '/confirm_email',    to: 'users#confirm_email', via: 'get'

  match '/password_reset_request',    to: 'sessions#new_password_reset_request', via: 'get'
  match '/password_reset_request',    to: 'sessions#create_password_reset_request', via: 'post'
  match '/reset_password',    to: 'sessions#reset_password', via: 'get'
  match '/reset_password',    to: 'sessions#update_password', via: 'post'

end

app/views/layouts/_footer.html.haml
%footer.footer
  %nav
    %ul
      -#%li= link_to I18n.t('layout.about'), about_path
      %li= link_to I18n.t('layout.contact'), contact_path

app/views/layouts/_head.html.haml
%head
  %title= full_title(yield(:title))
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  = favicon_link_tag 'favicon3.ico'

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to I18n.t('application.logo'), root_path, class: "navbar-brand", id: "logo"
    - if signed_in?
      %ul.nav.navbar-nav.pull-left
        %li= link_to I18n.t('layout.home'), root_path, data: { keybinding: access_key(:home)}
        %li= link_to( new_card_path, data: { keybinding: access_key(:new_card)}, rel: I18n.t("monitor.global_controls.new_cards_link")){ haml_tag :span, :class => "glyphicon glyphicon-plus"; haml_concat Card.model_name.human}
        %li= link_to( new_list_path, data: { keybinding: access_key(:new_list)}, rel: I18n.t("monitor.global_controls.new_cards_link")){ haml_tag :span, :class => "glyphicon glyphicon-plus"; haml_concat List.model_name.human}
      %ul.nav.navbar-nav.pull-right
        %li= link_to I18n.t('layout.help'), help_path
        %li= link_to I18n.t('layout.kbshortcuts'), kbshortcuts_path, data: { keybinding: access_key(:kbs)}
        %li.dropdown#fat-menu
          %a.dropdown-toggle{ "data-toggle" => "dropdown" }
            = I18n.t('layout.account')
            %b.caret
          %ul.dropdown-menu{ "role" => "menu" }
            %li= link_to I18n.t('layout.profile'), current_user
            %li= link_to I18n.t('layout.export'), export_cards_path(format: :csv)
            %li.divider
            %li= link_to I18n.t('layout.signout'), signout_path, method: :delete
    - else
      %ul.nav.navbar-nav.pull-right
        %li= link_to I18n.t('layout.signup'), signup_path
        %li= link_to I18n.t('layout.signin'), signin_path

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/head'
  %body
    = render 'layouts/header' 
    = yield :out_of_container
    .container{ "role" => "main" }
      - flash.select{|k,v| %w{success warning error info}.include? k}.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}") 
      = yield
      = render 'layouts/footer' 
      = debug(@debug) if admin? and @debug
      -#= method(:debug)
      -# str = PP.pp( @debug, "") # to be wrapped in pre